---

provisioner:
  name: chef_solo

platforms:
  - name: server
    driver: ssh
    driver_config:
      hostname: <%= ENV['EC2DREAM_HOSTNAME'] %>
      username: root
      ssh_key: C:/repository/keys/test.pem
  - name: ubuntu-12.04
    driver:  vagrant
  - name: centos-6.3
    driver:  vagrant
  - name: centos-6.4
    driver:  vagrant
  - name: ec2-ubuntu-12.04
    driver: ec2
    driver_config:
      image_id: ami-fd20ad94
      username: ubuntu
      aws_access_key_id: XXXXXXXXXXXXXX
      aws_secret_access_key: YYYYYYYYYYYYYYYYYYYYYY
      aws_ssh_key_id: test
      ssh_key: C:/repository/keys/test.pem
      security_group_ids: ["sg-xxxxxxxx"]
      region: us-east-1
      availability_zone: us-east-1d
      flavor_id: t1.micro
      require_chef_omnibus: true
      subnet_id: subnet-xxxxxxx
  - name: ec2-centos-6.3
    driver: ec2
    driver_config:
      image_id: ami-ef5ff086
      username: ec2-user
      aws_access_key_id: XXXXXXXXXXXXXX
      aws_secret_access_key: YYYYYYYYYYYYYYYYYYYYYY
      aws_ssh_key_id: test
      ssh_key: C:/repository/keys/test.pem
      security_group_ids: ["sg-xxxxxxxx"]
      region: us-east-1
      availability_zone: us-east-1d
      flavor_id: t1.micro
      require_chef_omnibus: true
      subnet_id: subnet-xxxxxxx

suites:
  - name: default
    run_list:
      - recipe[mycompany_webserver]
    attributes:
